<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PVSTEKST</AssemblyName>
    <RootNamespace>PvsTekstApp</RootNamespace>
    <ApplicationIcon>pvstekst.ico</ApplicationIcon>
    <Product>ПВ-Система Текст</Product>
    <Company>ПВ-Система</Company>
    <AssemblyTitle>ПВ-Система Текст</AssemblyTitle>
    <Copyright>ПВ-Система</Copyright>
    <SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
  </ItemGroup>

  <ItemGroup Condition="Exists('pvstekst.ico')">
    <None Update="pvstekst.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
